Repository gardener/gardenctl, pull requests merged in 2019-03, with the labels that each got.

#65 Update golang to 1.12.0
  .ci/pipeline_definitions
  Dockerfile
Labels: area/security, component/gardenctl, needs/ok-to-test, needs/review, size/xs, status/accepted

#67 Improve shell command
  cmd/shell.go
Labels: area/ops-productivity, component/gardenctl, exp/beginner, kind/bug, priority/normal, reviewed/do-not-merge, size/xs, status/accepted

#70 integrate aliyun cli with gardenctl
  cmd/aliyun.go
  cmd/operate.go
  cmd/root.go
Labels: component/gardenctl, exp/beginner, kind/enhancement, platform/ali
