Repository gardener/gardenctl, pull requests merged in 2020-12, with the labels that each got.

#467 fix several gardenctl ssh aws issue
  pkg/cmd/ssh_aws.go
  pkg/cmd/utils.go
Labels: needs/ok-to-test, size/xs

#468 fix conflict action
  .github/workflows/conflict.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#476 Condense commands in `gardenctl infra orphan list`
  pkg/cmd/orphan.go
  pkg/cmd/orphan_test.go
  pkg/cmd/root.go
Labels: needs/ok-to-test, needs/review, size/s

#481 enhance help method for gardenctl
  pkg/cmd/aliyun.go
  pkg/cmd/aws.go
  pkg/cmd/az.go
  pkg/cmd/completion.go
  pkg/cmd/diag.go
  pkg/cmd/download.go
  pkg/cmd/drop.go
  pkg/cmd/gcloud.go
  pkg/cmd/get.go
  pkg/cmd/info.go
  pkg/cmd/kubectl.go
  pkg/cmd/kubectx.go
  pkg/cmd/logs.go
  pkg/cmd/ls.go
  pkg/cmd/openstack.go
  pkg/cmd/orphan.go
  pkg/cmd/register.go
  pkg/cmd/shell.go
  pkg/cmd/show.go
  pkg/cmd/ssh.go
  pkg/cmd/target.go
  pkg/cmd/terraform.go
  pkg/cmd/unregister.go
  pkg/cmd/update-check.go
  pkg/cmd/version.go
Labels: needs/ok-to-test, needs/review, size/s

#485 add AliCloud
  .github/gardener_clusters/gctl-ali.yaml
Labels: needs/ok-to-test, needs/review, size/s

#487 Fix kubeconfig leak
  pkg/cmd/kubeconfig_writer.go
Labels: kind/bug, needs/ok-to-test, needs/review, size/xs

#488 Add strict .gitignore
  .gitignore
Labels: needs/ok-to-test, needs/review, size/s

#471 enable gardenctl logs for some components while targeting the control plane
  pkg/cmd/logs.go
  pkg/cmd/miscellaneous.go
Labels: needs/ok-to-test, needs/review, size/m

#473 Rename categories in pull request template
  .github/pull_request_template.md
Labels: area/dev-productivity, kind/enhancement, needs/ok-to-test, priority/normal, reviewed/lgtm, size/xs

#491 more strict gitignore
  .gitignore
Labels: needs/ok-to-test, needs/review, size/xs

#498 Enable ssh a VM when it can't register as a kube node on Alicloud
  pkg/cmd/ssh_alicloud.go
Labels: needs/ok-to-test, needs/review, size/xs
