Repository gardener/gardenctl, pull requests merged in 2020-11, with the labels that each got.

#408 Gactl shoot
  .github/actions/k8s/action.yml
  .github/gardener_clusters/gctl-aws.yaml
  .github/gardener_clusters/gctl-az.yaml
  .github/gardener_clusters/gctl-gcp.yaml
  .github/gardener_clusters/gctl-os.yaml
  .github/workflows/deploy-gardener-cluster.yml
Labels: needs/ok-to-test, needs/second-opinion, size/l

#430 Fix github action pipeline
  .github/actions/k8s/action.yml
  .github/gardener_clusters/gctl-aws.yaml
  .github/gardener_clusters/gctl-az.yaml
  .github/gardener_clusters/gctl-gcp.yaml
  .github/gardener_clusters/gctl-os.yaml
  .github/workflows/deploy-gardener-cluster.yml
Labels: needs/ok-to-test, needs/review, size/xs

#413 gardenctl diag command
  go.mod
  go.sum
  pkg/cmd/diag.go
  pkg/cmd/root.go
  vendor/github.com/mattn/go-runewidth/.travis.yml
  vendor/github.com/mattn/go-runewidth/LICENSE
  vendor/github.com/mattn/go-runewidth/README.mkd
  vendor/github.com/mattn/go-runewidth/go.mod
  vendor/github.com/mattn/go-runewidth/runewidth.go
  vendor/github.com/mattn/go-runewidth/runewidth_appengine.go
  vendor/github.com/mattn/go-runewidth/runewidth_js.go
  vendor/github.com/mattn/go-runewidth/runewidth_posix.go
  vendor/github.com/mattn/go-runewidth/runewidth_table.go
  vendor/github.com/mattn/go-runewidth/runewidth_windows.go
  vendor/github.com/olekukonko/tablewriter/.gitignore
  vendor/github.com/olekukonko/tablewriter/.travis.yml
  vendor/github.com/olekukonko/tablewriter/LICENSE.md
  vendor/github.com/olekukonko/tablewriter/README.md
  vendor/github.com/olekukonko/tablewriter/csv.go
  vendor/github.com/olekukonko/tablewriter/go.mod
  vendor/github.com/olekukonko/tablewriter/go.sum
  vendor/github.com/olekukonko/tablewriter/table.go
  vendor/github.com/olekukonko/tablewriter/table_with_color.go
  vendor/github.com/olekukonko/tablewriter/util.go
  vendor/github.com/olekukonko/tablewriter/wrap.go
  vendor/k8s.io/metrics/LICENSE
  vendor/k8s.io/metrics/pkg/apis/metrics/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/clientset.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/register.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/podmetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/podmetrics.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/second-opinion, size/l

#423 add passing custom arguments - aws/gcp/az
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_azure.go
  pkg/cmd/ssh_gcp.go
Labels: needs/ok-to-test, size/xs

#424 allow pass args to ssh openstack node
  pkg/cmd/ssh_openstack.go
Labels: needs/ok-to-test, size/xs

#428 remove double dash when using gardenctl aws/gcloud/az/openstack/kubectl
  pkg/cmd/aws.go
  pkg/cmd/az.go
  pkg/cmd/gcloud.go
  pkg/cmd/kubectl.go
  pkg/cmd/openstack.go
Labels: needs/ok-to-test, size/s

#435 Validate GARDENCONFIG path set explicitly before usage
  pkg/cmd/root.go
Labels: needs/ok-to-test, size/xs

#441 enable loki-0 for cluster
  .github/gardener_clusters/gctl-gcp.yaml
Labels: needs/changes, reviewed/ok-to-test, size/xs

#425 Issue 326 sanitize logs go
  pkg/cmd/logs.go
  pkg/cmd/logs_test.go
Labels: needs/changes, needs/ok-to-test, needs/second-opinion, size/m

#437 enable gardenctl logs all to download all logs to current dir/logs folder
  pkg/cmd/logs.go
  pkg/cmd/utils.go
Labels: needs/ok-to-test, needs/review, needs/second-opinion, reviewed/ok-to-test, size/l

#449 add error check to f.Sync()
  pkg/cmd/logs.go
Labels: needs/review, reviewed/ok-to-test, size/xs

#438 fix golangci-lint check error
  pkg/cmd/get.go
  pkg/cmd/info.go
  pkg/cmd/logs.go
  pkg/cmd/ssh.go
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/xs

#404 refactor functions and add test case in miscellaneous.go & miscellaneous_test.go and others which impacted
  .ci/test
  .ci/test_local
  pkg/cmd/download.go
  pkg/cmd/get.go
  pkg/cmd/get_test.go
  pkg/cmd/infra.go
  pkg/cmd/logs.go
  pkg/cmd/logs_test.go
  pkg/cmd/miscellaneous.go
  pkg/cmd/miscellaneous_test.go
  pkg/cmd/root.go
  pkg/cmd/show.go
  pkg/cmd/ssh.go
  pkg/cmd/ssh_alicloud.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_azure.go
  pkg/cmd/ssh_gcp.go
  pkg/cmd/target.go
  pkg/cmd/utils.go
Labels: needs/changes, needs/ok-to-test, needs/second-opinion, size/xl

#445 cleanup function will return the code which ssh returns
  pkg/cmd/ssh_openstack.go
  pkg/cmd/utils.go
Labels: needs/changes, needs/ok-to-test, size/s

#451 exit and print error message when seed.spec.SecretRef unavailable
  pkg/cmd/target.go
Labels: needs/ok-to-test, size/xs

#431 Make logPodSeed use the current context
  pkg/cmd/logs.go
Labels: needs/changes, needs/ok-to-test, size/xs

#440 Add script to test ssh functionality
  .ci/test
  .ci/test_ssh
  pkg/cmd/get_test.go
  pkg/cmd/ls_test.go
Labels: needs/ok-to-test, size/s

#456 Fix 431 PR merge
  pkg/cmd/logs.go
Labels: needs/ok-to-test, size/xs

#454 Issue 433 logs loki
  pkg/cmd/logs.go
  pkg/cmd/logs_test.go
  pkg/cmd/utils.go
Labels: needs/ok-to-test, size/s

#446 fix aws ssh issue
  pkg/cmd/ssh_aws.go
  pkg/cmd/utils.go
Labels: needs/changes, needs/ok-to-test, size/s

#462 Update to golang 1.15 and tidy mods
  go.mod
  vendor/github.com/ghodss/yaml/.gitignore
  vendor/github.com/ghodss/yaml/.travis.yml
  vendor/github.com/ghodss/yaml/LICENSE
  vendor/github.com/ghodss/yaml/README.md
  vendor/github.com/ghodss/yaml/fields.go
  vendor/github.com/ghodss/yaml/yaml.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/kubernetes/fake/clientset_generated.go
  vendor/modules.txt
Labels: needs/ok-to-test, size/xs

#453 pr conflict-check
  .github/actions/conflict.yaml
Labels: needs/ok-to-test, size/xs

#464 gitignore updated
  .gitignore
Labels: needs/ok-to-test, size/xs

#461 ssh param providerid
  pkg/cmd/ssh.go
  pkg/cmd/ssh_alicloud.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_azure.go
  pkg/cmd/ssh_gcp.go
  pkg/cmd/ssh_openstack.go
Labels: needs/ok-to-test, needs/review, size/m
