Repository gardener/gardenctl, pull requests merged in 2020-09, with the labels that each got.

#263 non operator able to target and ssh node through bastion host
  pkg/cmd/download.go
  pkg/cmd/miscellaneous.go
  pkg/cmd/operate.go
  pkg/cmd/show.go
  pkg/cmd/ssh.go
  pkg/cmd/ssh_alicloud.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_azure.go
  pkg/cmd/ssh_gcp.go
  pkg/cmd/target.go
Labels: needs/ok-to-test, reviewed/lgtm

#276 Ipv4 check
  pkg/cmd/miscellaneous.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_gcp.go
Labels: needs/ok-to-test, reviewed/lgtm

#296 fix logic covering both garden+seed+shoot and garden+project+shoot
  pkg/cmd/operate.go
Labels: needs/ok-to-test, reviewed/lgtm

#298 fix logic missing check seed name while choosing shoot
  pkg/cmd/operate.go
Labels: needs/ok-to-test

#293 replace kubectl in getRole()
  pkg/cmd/miscellaneous.go
Labels: needs/ok-to-test

#303 integration between gardenctl and homebrew-tap
  .github/workflows/update-gardenctl.yml
Labels: needs/ok-to-test

#292 Fix publicipaddress return
  pkg/cmd/miscellaneous.go
  pkg/cmd/ssh_aws.go
Labels: needs/ok-to-test, reviewed/lgtm

#290 fix logic when current stack is garden+seed+namespace
  pkg/cmd/download.go
  pkg/cmd/logs.go
  pkg/cmd/show.go
Labels: needs/ok-to-test

#305 user role access azure node
  pkg/cmd/ssh_azure.go
Labels: needs/ok-to-test

#297 user role able to access GCP
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_gcp.go
Labels: needs/ok-to-test, reviewed/lgtm

#300 check cloud provider cli whether installed on local env
  pkg/cmd/aws.go
  pkg/cmd/az.go
  pkg/cmd/gcloud.go
  pkg/cmd/openstack.go
  pkg/cmd/utils.go
Labels: needs/ok-to-test, reviewed/lgtm

#264 enable ssh debug and Error msg debug
  pkg/cmd/root.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/utils.go
Labels: needs/ok-to-test

#308 refactor download/terraform and add test case for download
  pkg/cmd/download.go
  pkg/cmd/download_test.go
  pkg/cmd/root.go
  pkg/cmd/ssh.go
  pkg/cmd/terraform.go
Labels: needs/ok-to-test

#311 refactor target.go to prevent user role for targeting seed
  pkg/cmd/target.go
Labels: needs/ok-to-test

#310 refactor show.go and add test case for gardenctl show
  pkg/cmd/root.go
  pkg/cmd/show.go
  pkg/cmd/show_test.go
Labels: needs/ok-to-test

#316 add test case for log command
  pkg/cmd/download.go
  pkg/cmd/logs.go
  pkg/cmd/logs_test.go
Labels: needs/ok-to-test

#314 sanitize_267_ls_refactor
  pkg/cmd/ls.go
Labels: needs/ok-to-test, reviewed/lgtm

#313 sanitize_267_download_refactor
  pkg/cmd/download.go
Labels: needs/ok-to-test, reviewed/lgtm

#324 santize user input in ExeCmdXXX for drop.go
  pkg/cmd/drop.go
Labels: needs/ok-to-test, reviewed/lgtm

#331 santize user input in ExeCmdXXX for target.go
  pkg/cmd/target.go
Labels: needs/ok-to-test, reviewed/lgtm

#334 santize user input in ExeCmdXXX for show.go
  pkg/cmd/show.go
Labels: needs/ok-to-test, reviewed/ok-to-test

#335 Fix getRole
  pkg/cmd/miscellaneous.go
Labels: needs/ok-to-test, reviewed/lgtm

#304 list orphaned resources
  pkg/cmd/infra.go
  pkg/cmd/infra_test.go
  pkg/cmd/root.go
Labels: needs/ok-to-test, reviewed/lgtm

#332 add logs gardenlet
  pkg/cmd/logs.go
  pkg/cmd/logs_test.go
Labels: needs/ok-to-test, reviewed/lgtm

#321 add -v -progress to show detailed information for each test case
  .ci/test
Labels: kind/test, needs/ok-to-test

#337 Revert "list orphaned resources"
  pkg/cmd/infra.go
  pkg/cmd/infra_test.go
  pkg/cmd/root.go
Labels: reviewed/ok-to-test

#340 List orphaned infra resources
  pkg/cmd/infra.go
  pkg/cmd/infra_test.go
  pkg/cmd/root.go
Labels: needs/ok-to-test, reviewed/lgtm

#343 fix go fmt issue in infra.go and infra_test.go
  pkg/cmd/infra.go
  pkg/cmd/infra_test.go
Labels: needs/ok-to-test

#342 remove elasticsearch from gardenctl logs
  pkg/cmd/logs.go
  pkg/cmd/logs_test.go
Labels: needs/ok-to-test

#349 remove kibana
  pkg/cmd/miscellaneous.go
  pkg/cmd/show.go
Labels: needs/ok-to-test, reviewed/lgtm

#351 g infra orphan list GCP support
  pkg/cmd/infra.go
Labels: needs/ok-to-test, reviewed/lgtm

#360 OpenStack support for listing orphaned resources
  pkg/cmd/infra.go
Labels: needs/ok-to-test, reviewed/lgtm
