Repository gardener/gardenctl, pull requests merged in 2020-08, with the labels that each got.

#246 remove extra () per go fmt hint
  pkg/cmd/terraform.go
Labels: needs/ok-to-test

#247 fix nc hanging and cleanup
  pkg/cmd/ssh_aws.go
Labels: needs/ok-to-test, reviewed/lgtm

#250 add logging package github.com/gardener/gardener/pkg/logger
  go.sum
  vendor/github.com/gardener/gardener/pkg/logger/logger.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/LICENSE
  vendor/github.com/konsorten/go-windows-terminal-sequences/README.md
  vendor/github.com/konsorten/go-windows-terminal-sequences/go.mod
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences.go
  vendor/github.com/konsorten/go-windows-terminal-sequences/sequences_dummy.go
  vendor/github.com/sirupsen/logrus/.gitignore
  vendor/github.com/sirupsen/logrus/.travis.yml
  vendor/github.com/sirupsen/logrus/CHANGELOG.md
  vendor/github.com/sirupsen/logrus/LICENSE
  vendor/github.com/sirupsen/logrus/README.md
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/sirupsen/logrus/doc.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/formatter.go
  vendor/github.com/sirupsen/logrus/go.mod
  vendor/github.com/sirupsen/logrus/go.sum
  vendor/github.com/sirupsen/logrus/hooks.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_appengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
  vendor/github.com/sirupsen/logrus/writer.go
  vendor/modules.txt
Labels: needs/ok-to-test

#254 Limit SSH node security group to Bastion IP
  pkg/cmd/ssh_aws.go
Labels: reviewed/lgtm

#244 pass cloud cli creds as args only
  pkg/cmd/operate.go
Labels: needs/ok-to-test

#258 Revert "Limit SSH node security group to Bastion IP"
  pkg/cmd/ssh_aws.go
Labels: needs/ok-to-test

#213 Adapt logs command to Loki
  pkg/cmd/logs.go
  pkg/cmd/miscellaneous.go
  vendor/k8s.io/client-go/kubernetes/clientset.go
  vendor/k8s.io/client-go/kubernetes/fake/clientset_generated.go
Labels: needs/ok-to-test, reviewed/lgtm

#245 add restriction support like eu-access restriction
  pkg/cmd/target.go
  pkg/cmd/types.go
Labels: needs/ok-to-test, reviewed/lgtm

#262 add global debug switch and GardenctlDebugLog / GardenctlInfoLog function
  pkg/cmd/root.go
  pkg/cmd/utils.go
Labels: needs/ok-to-test

#274 refactor curl to use net/http
  pkg/cmd/miscellaneous.go
Labels: needs/ok-to-test, reviewed/lgtm

#280 remove url.QueryEscape
  pkg/cmd/miscellaneous.go
Labels: needs/ok-to-test, reviewed/lgtm

#202 Add github action to update gardenctl homebrew-tap
  .github/workflows/update-gardenctl.yml
Labels: lifecycle/stale, needs/ok-to-test

#285 Add dashboardUrl and accessRestrictions in sample gardenctl config
  README.md
Labels: needs/ok-to-test
