Repository gardener/gardenctl, pull requests merged in 2020-07, with the labels that each got.

#218 Remove AWS instance profile from bastion nodes
  pkg/cmd/ssh_aws.go
Labels: needs/ok-to-test, reviewed/lgtm

#219 Add terraform subcommand
  pkg/cmd/root.go
  pkg/cmd/terraform.go
Labels: reviewed/lgtm

#215 Add pipeline job for automatic creation and publish of gardenctl docker image
  .ci/pipeline_definitions
Labels: reviewed/lgtm

#221 remove exec and auth provider check to utilize kubeconfig with oidc enabled
  pkg/cmd/utils.go
Labels: area/security, kind/discussion, needs/ok-to-test, reviewed/lgtm

#226 restrict Public IP when use ssh access cloud
  pkg/cmd/miscellaneous.go
  pkg/cmd/ssh.go
  pkg/cmd/ssh_alicloud.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_azure.go
  pkg/cmd/ssh_gcp.go
Labels: needs/ok-to-test, reviewed/lgtm

#228 add documentation for how to enable source completion in zsh
  README.md
Labels: needs/ok-to-test, reviewed/lgtm

#231 SSH code optimization
  pkg/cmd/ssh_aws.go
Labels: needs/ok-to-test, reviewed/lgtm

#237 use gardenctl-maintainers group
  CODEOWNERS
Labels: needs/ok-to-test

#239 fix ssh issue user => bastion
  pkg/cmd/ssh_aws.go
Labels: needs/ok-to-test, reviewed/lgtm
