Repository gardener/gardenctl, pull requests merged in 2020-10, with the labels that each got.

#367 Alicloud support for (g infra orphan list)
  pkg/cmd/infra.go
Labels: needs/ok-to-test, reviewed/lgtm

#319 refactor getTechnicalID
  pkg/cmd/get.go
  pkg/cmd/infra.go
  pkg/cmd/logs.go
  pkg/cmd/miscellaneous.go
  pkg/cmd/root.go
  pkg/cmd/show.go
  pkg/cmd/ssh_alicloud.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_azure.go
  pkg/cmd/ssh_gcp.go
Labels: needs/ok-to-test, reviewed/lgtm

#371 add getTargetMapInfo getTargetName isTargeted getFromTargetInfo
  pkg/cmd/get.go
  pkg/cmd/infra.go
  pkg/cmd/logs.go
  pkg/cmd/miscellaneous.go
  pkg/cmd/root.go
  pkg/cmd/show.go
  pkg/cmd/ssh_alicloud.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_azure.go
  pkg/cmd/ssh_gcp.go
Labels: needs/ok-to-test, reviewed/lgtm, size/m

#376 add logPodShoot function
  pkg/cmd/logs.go
Labels: needs/ok-to-test, reviewed/lgtm, reviewed/ok-to-test, size/xs

#377 add logPodSeed function and change logPodSeed
  pkg/cmd/logs.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#368 refactor ssh_aws remove capture()
  pkg/cmd/operate.go
  pkg/cmd/ssh_aws.go
  pkg/cmd/ssh_azure.go
  pkg/cmd/ssh_gcp.go
Labels: needs/ok-to-test, reviewed/lgtm

#378 fix alicloud sshkey inaccessible due to missing a /
  pkg/cmd/ssh_alicloud.go
Labels: needs/changes, needs/ok-to-test, size/xs

#380 fix gardenctl ssh alicloud node timed out issue
  pkg/cmd/ssh_alicloud.go
Labels: needs/ok-to-test, size/xs

#384 send release notes to both #sap-tech-gardener and #sap-tech-gardenctl channels
  .ci/pipeline_definitions
Labels: needs/changes, needs/ok-to-test, size/xs

#390 hotfix to https://github.com/gardener/gardenctl/issues/389
  pkg/cmd/operate.go
Labels: needs/ok-to-test, size/xs

#391 aws.go az.go gcloud.go
  .ci/test
  pkg/cmd/aws.go
  pkg/cmd/az.go
  pkg/cmd/gcloud.go
  pkg/cmd/operate.go
Labels: needs/ok-to-test, reviewed/lgtm, size/s

#399 Add documentation for gardenctl ssh
  README.md
Labels: needs/ok-to-test, size/xs

#398 remove release msg from #sap-tech-gardener slack channel
  .ci/pipeline_definitions
Labels: needs/ok-to-test, size/xs

#397 gardenctl ssh for openstack node
  pkg/cmd/openstack.go
  pkg/cmd/operate.go
  pkg/cmd/ssh.go
  pkg/cmd/ssh_openstack.go
Labels: needs/ok-to-test, reviewed/do-not-merge, size/m

#405 remove alertmanager related code
  README.md
  pkg/cmd/logs.go
  pkg/cmd/logs_test.go
  pkg/cmd/show.go
  pkg/cmd/show_test.go
Labels: needs/ok-to-test, size/s

#386 add more generic taints
  pkg/cmd/shell.go
Labels: needs/ok-to-test, size/xs

#412 Do not use deprecated project name label
  pkg/cmd/target.go
Labels: needs/ok-to-test, size/xs

#410 inspect and refactor ls.go
  pkg/cmd/ls.go
  pkg/cmd/ls_test.go
  pkg/cmd/operate.go
  pkg/cmd/target.go
  pkg/cmd/utils.go
  pkg/cmd/utils_test.go
Labels: needs/ok-to-test, reviewed/lgtm, size/m
