Repository gardener/gardenctl, pull requests merged in 2021-09, with the labels that each got.

#520 Clean up unused var
  pkg/cmd/ssh_alicloud.go
Labels: kind/cleanup, reviewed/lgtm, needs/ok-to-test, size/xs

#518 Hcloud command
  Makefile
  pkg/cmd/hcloud.go
  pkg/cmd/operate.go
  pkg/cmd/root.go
Labels: size/s, needs/review, needs/ok-to-test

#523 show error when failed to clean ops-pod
  pkg/cmd/shell.go
Labels: needs/review, needs/ok-to-test, size/xs
