Repository gardener/gardenctl, pull requests merged in 2021-05, with the labels that each got.

#515 Ensure shell command pod names are lowercase
  pkg/cmd/shell.go
Labels: needs/ok-to-test, needs/review, size/xs

#513 bugfix invoking logs fails
  pkg/cmd/logs.go
Labels: needs/ok-to-test, reviewed/lgtm, size/xs

#494 check whether ingress rule exist before adding it
  pkg/cmd/ssh_aws.go
Labels: needs/ok-to-test, needs/review, reviewed/ok-to-test, size/xs

#483 KC-432
  pkg/cmd/show.go
Labels: needs/ok-to-test, needs/review, size/xs

#504 Gactl cluster
  .github/gardener_clusters/gctl-ali.yaml
  .github/gardener_clusters/gctl-aws.yaml
  .github/gardener_clusters/gctl-az.yaml
  .github/gardener_clusters/gctl-gcp.yaml
  .github/gardener_clusters/gctl-os.yaml
  .github/workflows/deploy-gardener-cluster.yml
Labels: needs/ok-to-test, needs/review, size/xs

#495 Add garden show infra cmd
  pkg/cmd/operate.go
  pkg/cmd/show.go
  pkg/cmd/show_test.go
Labels: needs/ok-to-test, needs/review, size/m
